const text = [
  `Blog single-origin coffee keffiyeh disrupt air plant. Actually 90's beard, four loko enamel pin salvia dreamcatcher hexagon sartorial prism mumblecore. Raw denim schlitz shoreditch lumbersexual cliche kickstarter pop-up beard hot chicken polaroid street art prism DIY yr. Everyday carry direct trade post-ironic iPhone meggings godard actually food truck kale chips hexagon poutine. Prism meditation freegan letterpress thundercats seitan. Roof party 3 wolf moon dreamcatcher ennui swag tacos, four loko woke meh gochujang photo booth.`,
  `Raw denim organic DIY marfa polaroid selfies hella retro hexagon fashion axe. Copper mug literally umami before they sold out yr DIY. Farm-to-table single-origin coffee art party air plant, vice austin tbh fixie iPhone squid leggings everyday carry flexitarian locavore. Post-ironic live-edge wolf, meggings narwhal tofu cronut selvage pok pok mlkshk selfies sriracha.`,
  `Live-edge fingerstache keffiyeh XOXO af, photo booth pinterest williamsburg. Offal biodiesel beard adaptogen tumblr VHS activated charcoal hashtag pork belly. Tattooed pabst lumbersexual raclette mustache squid prism authentic health goth semiotics paleo post-ironic. Pop-up cronut lumbersexual, kombucha edison bulb small batch forage lyft godard subway tile sriracha adaptogen.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `Artisan street art vaporware palo santo air plant mixtape schlitz green juice la croix polaroid brunch four dollar toast. Ethical humblebrag cardigan portland pop-up salvia. Pour-over pug fam hella, seitan readymade woke. Stumptown knausgaard tacos, godard ramps pork belly banjo hammock craft beer.`,
  `Banh mi swag readymade hoodie everyday carry live-edge kinfolk. Cardigan truffaut sartorial mlkshk. Tousled williamsburg blog cold-pressed celiac, hella VHS offal yuccie small batch. Tofu craft beer letterpress, forage 3 wolf moon schlitz farm-to-table yr vexillologist palo santo hammock occupy tumeric pork belly gentrify. Microdosing flannel occupy quinoa hot chicken, umami typewriter glossier photo booth put a bird on it locavore schlitz plaid palo santo. Viral squid thundercats, tilde vice biodiesel pok pok shaman literally whatever hammock copper mug mustache pitchfork. Shabby chic leggings taxidermy tattooed helvetica shaman glossier, distillery pork belly 3 wolf moon salvia church-key artisan put a bird on it.`,
  `PBR&B tacos etsy, tumblr selvage offal skateboard woke roof party. Small batch mustache organic intelligentsia affogato shaman wolf neutra raw denim everyday carry occupy gastropub thundercats craft beer bushwick. Post-ironic everyday carry squid, knausgaard yr hashtag pickled gochujang. Before they sold out pitchfork art party celiac dreamcatcher, fam freegan man bun. Fam williamsburg tumeric mixtape swag tacos. Blue bottle tote bag lyft drinking vinegar man braid typewriter sartorial, celiac tumblr freegan cloud bread. Activated charcoal kogi tumeric taxidermy direct trade, vape letterpress dreamcatcher yuccie street art beard chicharrones fingerstache art party post-ironic.`,
  `DIY selvage etsy, neutra butcher cliche vinyl green juice leggings hexagon. Iceland shoreditch echo park, wolf listicle mustache marfa scenester organic unicorn neutra readymade viral intelligentsia. Semiotics DIY neutra, hashtag microdosing lomo austin post-ironic PBR&B offal. Photo booth synth beard post-ironic before they sold out ugh try-hard, cloud bread artisan gluten-free shaman flexitarian typewriter. Microdosing raclette blue bottle lyft meggings put a bird on it church-key locavore craft beer glossier scenester cronut green juice taxidermy.`,
  `Ethical artisan XOXO quinoa fingerstache put a bird on it la croix poke cred brooklyn retro semiotics scenester cardigan biodiesel. Godard quinoa squid butcher succulents. Tousled meggings lo-fi listicle, 90's woke mumblecore ugh truffaut paleo migas offal vexillologist dreamcatcher kickstarter. Cliche migas coloring book photo booth mumblecore, umami fanny pack raw denim hexagon tumeric food truck shoreditch slow-carb irony. Cardigan dreamcatcher four loko austin squid beard four dollar toast pop-up gentrify pabst coloring book man braid activated charcoal green juice.`,`Gentrify slow-carb retro tumblr fingerstache. Disrupt chicharrones intelligentsia gentrify, umami meggings retro swag portland viral kickstarter street art echo park letterpress. Ethical messenger bag raw denim mumblecore tumblr tilde. Flannel jianbing williamsburg, stumptown ennui organic whatever tote bag af. Forage yr letterpress, snackwave austin lo-fi literally fanny pack small batch beard air plant everyday carry viral succulents lomo. Fingerstache jean shorts you probably haven't heard of them ethical tousled. Cred crucifix chambray aesthetic pork belly, poke banjo put a bird on it franzen cray.`,
];
export default text;
